apiVersion: v1
kind: Service
metadata:
  name: twittorservices-srv
spec:
  type: NodePort
  selector:
    app: twittorservice
  ports:
  - name: twittorservice
    protocol: TCP
    port: 80
    targetPort: 80