apiVersion: apps/v1
kind: Deployment
metadata:
  name: twittorservices-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twittorservice
  template:
    metadata:
      labels:
        app: twittorservice
    spec:
      containers:
      - name: twittorservice
        image: rizhy/twittorservice:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: twittorservices-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: twittorservice
  ports:
  - name: twittorservice
    protocol: TCP
    port: 80
    targetPort: 80